apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: poc-knative
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/ijrandom/poc-knative
          env:
            - name: TARGET
              value: "Spring Boot Sample v1"